2022-11-22 19:53:47,148 ERROR: Exception on /user/2 [GET] [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\main\routes.py", line 70, in user
    return render_template("main/user.html", user=user, posts=posts.items, \
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\main\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\base.html", line 49, in block 'content'
    {% block web_content %}{% endblock %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\main\user.html", line 16, in block 'web_content'
    {% elif current_user.is_following(user) %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'is_following'
2022-11-22 19:54:01,363 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-22 20:04:09,731 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-22 20:04:51,048 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-22 20:15:39,025 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 16:41:18,303 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 16:43:16,564 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 16:45:26,163 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 16:46:44,301 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:06:59,386 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:11:19,250 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:13:03,606 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:15:17,021 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:16:54,482 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:22:04,951 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:22:06,106 ERROR: Exception on /post_detail/2 [GET] [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\main\routes.py", line 128, in post_detail
    return render_template('main/post_detail.html', title="Post detail", post=post, \
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\main\post_detail.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\base.html", line 49, in block 'content'
    {% block web_content %}{% endblock %}
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\main\post_detail.html", line 45, in block 'web_content'
    <p>{% include "main/_comment.html" %}</p>
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\templates\main\_comment.html", line 1, in top-level template code
    <p><a href="{{ url_for('user', id=comment.author.id) }}">{{ comment.author.username }}</a></p>
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'user' with values ['id']. Did you mean 'main.user' instead?
2022-11-24 17:22:29,433 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:28:03,700 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
2022-11-24 17:29:14,436 ERROR: Exception on /post_detail/8 [POST] [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\web_env\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\main\routes.py", line 121, in post_detail
    c = Comment(comment=form.comment.data, post_id=post_id, user_id=current_user.id)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
2022-11-24 17:31:03,781 INFO: Website startup [in D:\TranXuanThuy\Project\ChiaSeDoCuWeb\website\__init__.py:67]
